USE [master]
GO

/****** Object:  Database [AlumnosCursosDB]    Script Date: 3/4/2019 05:38:26 ******/
DROP DATABASE [AlumnosCursosDB]
GO

/****** Object:  Database [AlumnosCursosDB]    Script Date: 3/4/2019 05:38:26 ******/
CREATE DATABASE [AlumnosCursosDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AlumnosCursosDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AlumnosCursosDB.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AlumnosCursosDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AlumnosCursosDB_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AlumnosCursosDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AlumnosCursosDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AlumnosCursosDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [AlumnosCursosDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AlumnosCursosDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AlumnosCursosDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AlumnosCursosDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AlumnosCursosDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [AlumnosCursosDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AlumnosCursosDB] SET  MULTI_USER 
GO

ALTER DATABASE [AlumnosCursosDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AlumnosCursosDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AlumnosCursosDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AlumnosCursosDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AlumnosCursosDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AlumnosCursosDB] SET  READ_WRITE 
GO


